sudo: enabled
language: node_js
node_js:
- "8"
install:
- curl https://install.meteor.com | /bin/sh
- cp "/home/travis/.meteor/packages/meteor-tool/1.6.1/mt-os.linux.x86_64/scripts/admin/launch-meteor" /usr/bin/meteor
- npm install
script:
- npm run eslint
- meteor test --driver-package meteortesting:mocha